version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://tallerPostgres:Laura2002@db:5432/students_db
    networks:
      - app-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=tallerPostgres
      - POSTGRES_PASSWORD=Laura2002
      - POSTGRES_DB=students_db
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: